### ISSUE TITLE
희수입니다.

### ISSUE THREAD

**Issue by ullookmal79** [galcyurio/Doodle_Project#11]
여러븐, 제거 휴대폰을 두고 와서 어떻게 연락할까하다가
깃헙에 올리면 혹시 누가 먼저 보시지 않을까해서 이렇게 글 씁니다. 죄송해요 ㅠㅜ
오늘 감기도 심해지고 학교 탐 과제도 있어서 수업에 못 갈 것 같습니다,
몸이 아프진 않은데 말이 안나오고 기침을 토할듯이 하기만 해요. 
늦게라도 가면 왠지 게임 하고 계실 거 같아서 
오늘 하루 프로젝트 못한대신 휴일동안 집에서 열심히 해오겠습니다.
그럼 오늘도 열공하세욥. 집에가면 연락드릴게요
죄송함니다.

**Comment by galcyurio** [comment]
확인했습니다
